export enum LEAGUE {
  ATL = "Atlanta Hawks",
  BOS = "Boston Celtics",
  BKN = "Brooklyn Nets",
  CHA = "Charlotte Hornets",
  CHI = "Chicago Bulls",
  CLE = "Cleveland Cavaliers",
  DAL = "Dallas Mavericks",
  DEN = "Denver Nuggets",
  DET = "Detroit Pistons",
  GSW = "Golden State Warriors",
  HOU = "Houston Rockets",
  IND = "Indiana Pacers",
  LAC = "LA Clippers",
  LAL = "Los Angeles Lakers",
  MEM = "Memphis Grizzlies",
  MIA = "Miami Heat",
  MIL = "Milwaukee Bucks",
  MIN = "Minnesota Timberwolves",
  NOP = "New Orleans Pelicans",
  NYK = "New York Knicks",
  OKC = "Oklahoma City Thunder",
  ORL = "Orlando Magic",
  PHI = "Philadelphia 76ers",
  PHX = "Phoenix Suns",
  POR = "Portland Trail Blazers",
  SAC = "Sacramento Kings",
  SAS = "San Antonio Spurs",
  TOR = "Toronto Raptors",
  UTA = "Utah Jazz",
  WAS = "Washington Wizards",
}
export enum apis {
  API_URL = "http://127.0.0.1:8080/",
  API_GK_URL = "https://nba-shotchart-2bc40.uc.r.appspot.com/",
}
export const teamColorSchemes = new Map<string, any>([
  ["Atlanta Hawks", { prim: "#E03A3E", sec: "#C1D32F", third: "#26282a" }],
  ["Boston Celtics", { prim: "#00a55c", sec: "#bb9753", third: "black" }],
  ["Brooklyn Nets", { prim: "black", sec: "white", third: "#a1a1a4" }],
  ["Charlotte Hornets", { prim: "#1d1160", sec: "#00788c", third: "#a1a1a4" }],
  ["Chicago Bulls", { prim: "#ce1141", sec: "black", third: "white" }],
  [
    "Cleveland Cavaliers",
    { prim: "#6f2633", sec: "#ffb81c", third: "#041e42" },
  ],
  ["Dallas Mavericks", { prim: "#0053bc", sec: "#00285e", third: "#c4ced" }],
  ["Denver Nuggets", { prim: "#244289", sec: "#ffc627", third: "#8b2131" }],
  ["Detroit Pistons", { prim: "#1d428a", sec: "#c8102e", third: "white" }],
  [
    "Golden State Warriors",
    { prim: "#006bb6", sec: "#fdb927", third: "#26282a" },
  ],
  ["Houston Rockets", { prim: "#ce1141", sec: "#c4ced4", third: "black" }],
  ["Indiana Pacers", { prim: "#002d62", sec: "#fdbb30", third: "#bec0c2" }],
  ["LA Clippers", { prim: "#1d428a", sec: "#c8102e", third: "white" }],
  ["Los Angeles Lakers", { prim: "#552583", sec: "#fdb927", third: "white" }],
  ["Memphis Grizzlies", { prim: "#12173f", sec: "#5d76a9", third: "#ffbb22" }],
  ["Miami Heat", { prim: "#98002e", sec: "#f9a01b", third: "black" }],
  ["Milwaukee Bucks", { prim: "#00471b", sec: "#eee1c6", third: "white" }],
  [
    "Minnesota Timberwolves",
    { prim: "#0c2340", sec: "#78be20", third: "white" },
  ],
  [
    "New Orleans Pelicans",
    { prim: "#002b5c", sec: "#b4975a", third: "#e31837" },
  ],
  ["New York Knicks", { prim: "#006bb6", sec: "#f58426", third: "white" }],
  [
    "Oklahoma City Thunder",
    { prim: "#007ac1", sec: "#ef3b24", third: "#002d62" },
  ],
  ["Orlando Magic", { prim: "#0b77bd", sec: "black", third: "white" }],
  ["Philadelphia 76ers", { prim: "#006bb6", sec: "#ed174c", third: "white" }],
  ["Phoenix Suns", { prim: "#1d1160", sec: "#e56020", third: "#63727a" }],
  ["Portland Trail Blazers", { prim: "#e03a3e", sec: "black", third: "white" }],
  ["Sacramento Kings", { prim: "#5a2b81", sec: "#63727a", third: "white" }],
  ["San Antonio Spurs", { prim: "#c4ced4", sec: "black", third: "white" }],
  ["Toronto Raptors", { prim: "#ce1141", sec: "#a1a1a4", third: "black" }],
  ["Utah Jazz", { prim: "#002b5c", sec: "#f9a01b", third: "#00471b" }],
  ["Washington Wizards", { prim: "#002b5c", sec: "#e31837", third: "#c4ced4" }],
]);

export enum Shot_Zones {
  Above_the_Break_3 = "Above the Break 3",
  Backcourt = "Backcourt",
  In_The_Paint_Non_RA = "In The Paint (Non-RA)",
  Left_Corner_3 = "Left Corner 3",
  Mid_Range = "Mid-Range",
  Restricted_Area = "Restricted Area",
  Right_Corner_3 = "Right Corner 3",
}

export const Quarters = [
  "1st Quarter",
  "2nd Quarter",
  "3rd Quarter",
  "4th Quarter",
  "OverTime",
  "Double Over Time",
];
